/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcms;

/**
 *
 * @author user
 */
public class lecturerLoginHome extends javax.swing.JFrame {

    /**
     * Creates new form lecturerLoginHome
     */
    public lecturerLoginHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fgText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fgText3 = new javax.swing.JLabel();
        enter = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText2.setBackground(new java.awt.Color(0, 0, 204));
        fgText2.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        fgText2.setForeground(new java.awt.Color(204, 204, 204));
        fgText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText2.setText("Lecturer1");
        getContentPane().add(fgText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 450, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/student Profile.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 170, 170));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSC401", "CSC444", "CSC441", "CSC404" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 400, 40));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select a course to continue");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 330, 30));

        fgText3.setBackground(new java.awt.Color(0, 0, 204));
        fgText3.setFont(new java.awt.Font("Poor Richard", 1, 60)); // NOI18N
        fgText3.setForeground(new java.awt.Color(204, 204, 204));
        fgText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText3.setText("WELCOME");
        getContentPane().add(fgText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 450, 60));

        enter.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        enter.setForeground(new java.awt.Color(204, 204, 204));
        enter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter.setText("Enter");
        enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterMouseExited(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 130, 30));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/new main blurr application background .png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
        
 lecturerHome home = new lecturerHome();
       home.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_enterMouseClicked

    private void enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseEntered
     enter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        enter.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_enterMouseEntered

    private void enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseExited
      enter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        enter.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_enterMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturerLoginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturerLoginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturerLoginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturerLoginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturerLoginHome().setVisible(true);
            }
        });
        
        
         
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel enter;
    private javax.swing.JLabel fgText2;
    private javax.swing.JLabel fgText3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
