/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcms;

/**
 *
 * @author user
 */
public class lecturerHome extends javax.swing.JFrame {

    /**
     * Creates new form lecturerHome
     */
    public lecturerHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fgText3 = new javax.swing.JLabel();
        fgText12 = new javax.swing.JLabel();
        fgText13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fgText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        assignmentBtn = new javax.swing.JLabel();
        infoBtn = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        inboxBtn = new javax.swing.JLabel();
        editProfile = new javax.swing.JLabel();
        GradesBtn = new javax.swing.JLabel();
        attendanceBtn = new javax.swing.JLabel();
        fgText16 = new javax.swing.JLabel();
        assignmentBtn1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lecturerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText3.setBackground(new java.awt.Color(0, 0, 204));
        fgText3.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        fgText3.setForeground(new java.awt.Color(204, 204, 204));
        fgText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText3.setText("Introduction to Advanced Web Programming");
        jPanel4.add(fgText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 790, 70));

        fgText12.setBackground(new java.awt.Color(0, 0, 204));
        fgText12.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText12.setForeground(new java.awt.Color(204, 204, 204));
        fgText12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText12.setText("CSC 401");
        jPanel4.add(fgText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 30));

        fgText13.setBackground(new java.awt.Color(0, 0, 204));
        fgText13.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText13.setForeground(new java.awt.Color(204, 204, 204));
        fgText13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText13.setText("Pick a menu item to begin");
        jPanel4.add(fgText13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 380, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 780, 440));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText2.setBackground(new java.awt.Color(0, 0, 204));
        fgText2.setFont(new java.awt.Font("Poor Richard", 1, 12)); // NOI18N
        fgText2.setForeground(new java.awt.Color(204, 204, 204));
        fgText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText2.setText("CSC401");
        jPanel2.add(fgText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/panel student Profile.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 90));

        signOut.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        signOut.setForeground(new java.awt.Color(204, 204, 204));
        signOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOut.setText("Sign Out");
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutMouseExited(evt);
            }
        });
        jPanel2.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, 20));

        assignmentBtn.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        assignmentBtn.setForeground(new java.awt.Color(204, 204, 204));
        assignmentBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignmentBtn.setText("ASSIGNMENTS");
        assignmentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        assignmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assignmentBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assignmentBtnMouseExited(evt);
            }
        });
        jPanel2.add(assignmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        infoBtn.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(204, 204, 204));
        infoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBtn.setText("INFORMATION");
        infoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });
        jPanel2.add(infoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        docBtn.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        docBtn.setForeground(new java.awt.Color(204, 204, 204));
        docBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        docBtn.setText("COURSE DOCUMENTS");
        docBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });
        jPanel2.add(docBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        inboxBtn.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        inboxBtn.setForeground(new java.awt.Color(204, 204, 204));
        inboxBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtn.setText("INBOX");
        inboxBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        inboxBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inboxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inboxBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inboxBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inboxBtnMouseExited(evt);
            }
        });
        jPanel2.add(inboxBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 30));

        editProfile.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        editProfile.setForeground(new java.awt.Color(204, 204, 204));
        editProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfile.setText("Edit Profile");
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        editProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        jPanel2.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 20));

        GradesBtn.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        GradesBtn.setForeground(new java.awt.Color(204, 204, 204));
        GradesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GradesBtn.setText("GRADES");
        GradesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        GradesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GradesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GradesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GradesBtnMouseExited(evt);
            }
        });
        jPanel2.add(GradesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        attendanceBtn.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        attendanceBtn.setForeground(new java.awt.Color(204, 204, 204));
        attendanceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendanceBtn.setText("ATTENDANCE");
        attendanceBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        attendanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceBtnMouseExited(evt);
            }
        });
        jPanel2.add(attendanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        fgText16.setBackground(new java.awt.Color(0, 0, 204));
        fgText16.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        fgText16.setForeground(new java.awt.Color(204, 204, 204));
        fgText16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText16.setText("Lecturer1");
        jPanel2.add(fgText16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 20));

        assignmentBtn1.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        assignmentBtn1.setForeground(new java.awt.Color(204, 204, 204));
        assignmentBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignmentBtn1.setText("ASSIGNMENTS");
        assignmentBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        assignmentBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignmentBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assignmentBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assignmentBtn1MouseExited(evt);
            }
        });
        jPanel2.add(assignmentBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 530));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturerID.setBackground(new java.awt.Color(102, 102, 102));
        lecturerID.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lecturerID.setForeground(new java.awt.Color(204, 204, 204));
        lecturerID.setText("Search");
        lecturerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        lecturerID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerIDMouseClicked(evt);
            }
        });
        lecturerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerIDActionPerformed(evt);
            }
        });
        jPanel3.add(lecturerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/search.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 40, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 780, 80));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/new main blurr application background .png"))); // NOI18N
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseClicked
        logInFrame login = new logInFrame();
        login.setVisible(true);
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        signOut.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_signOutMouseClicked

    private void signOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseEntered
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        signOut.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_signOutMouseEntered

    private void signOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseExited
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        signOut.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_signOutMouseExited

    private void assignmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtnMouseClicked
      lecturerAssignment assignment = new lecturerAssignment();
      assignment.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtnMouseClicked

    private void assignmentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtnMouseEntered
        assignmentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        assignmentBtn.setForeground(new java.awt.Color(153, 153, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtnMouseEntered

    private void assignmentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtnMouseExited
       assignmentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        assignmentBtn.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtnMouseExited

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseClicked

    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
      infoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        infoBtn.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
      infoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        infoBtn.setForeground(new java.awt.Color(204, 204, 204));   // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseExited

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
       docBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        docBtn.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
       docBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        docBtn.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseExited

    private void inboxBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inboxBtnMouseClicked

    private void inboxBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxBtnMouseEntered
       inboxBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        inboxBtn.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_inboxBtnMouseEntered

    private void inboxBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inboxBtnMouseExited
       inboxBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        inboxBtn.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_inboxBtnMouseExited

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseClicked

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        editProfile.setForeground(new java.awt.Color(153, 153, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        editProfile.setForeground(new java.awt.Color(204, 204, 204)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseExited

    private void GradesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseClicked

    private void GradesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseEntered
      GradesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        GradesBtn.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseEntered

    private void GradesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseExited
        GradesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        GradesBtn.setForeground(new java.awt.Color(204, 204, 204));// TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseExited

    private void attendanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceBtnMouseClicked

    private void attendanceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceBtnMouseEntered
       attendanceBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        attendanceBtn.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_attendanceBtnMouseEntered

    private void attendanceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceBtnMouseExited
       attendanceBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        attendanceBtn.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_attendanceBtnMouseExited

    private void lecturerIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerIDMouseClicked
        lecturerID.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDMouseClicked

    private void lecturerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDActionPerformed

    private void assignmentBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtn1MouseClicked

    private void assignmentBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtn1MouseEntered

    private void assignmentBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GradesBtn;
    private javax.swing.JLabel assignmentBtn;
    private javax.swing.JLabel assignmentBtn1;
    private javax.swing.JLabel attendanceBtn;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel docBtn;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel fgText12;
    private javax.swing.JLabel fgText13;
    private javax.swing.JLabel fgText16;
    private javax.swing.JLabel fgText2;
    private javax.swing.JLabel fgText3;
    private javax.swing.JLabel inboxBtn;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lecturerID;
    private javax.swing.JLabel signOut;
    // End of variables declaration//GEN-END:variables
}
