/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcms;

/**
 *
 * @author user
 */
public class lecturerAssignment extends javax.swing.JFrame {

    /**
     * Creates new form lecturerAssignment
     */
    public lecturerAssignment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lecturerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fgText3 = new javax.swing.JLabel();
        fgText12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        fgText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fgText4 = new javax.swing.JLabel();
        fgText6 = new javax.swing.JLabel();
        fgText7 = new javax.swing.JLabel();
        editProfile = new javax.swing.JLabel();
        fgText14 = new javax.swing.JLabel();
        fgText15 = new javax.swing.JLabel();
        fgText16 = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturerID.setBackground(new java.awt.Color(102, 102, 102));
        lecturerID.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lecturerID.setForeground(new java.awt.Color(204, 204, 204));
        lecturerID.setText("Search");
        lecturerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        lecturerID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerIDMouseClicked(evt);
            }
        });
        lecturerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerIDActionPerformed(evt);
            }
        });
        jPanel3.add(lecturerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/search.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 40, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 780, 80));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText3.setBackground(new java.awt.Color(0, 0, 204));
        fgText3.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText3.setForeground(new java.awt.Color(204, 204, 204));
        fgText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText3.setText("Viewed Assignment");
        jPanel4.add(fgText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 70));

        fgText12.setBackground(new java.awt.Color(0, 0, 204));
        fgText12.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText12.setForeground(new java.awt.Color(204, 204, 204));
        fgText12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText12.setText("New Assignments");
        jPanel4.add(fgText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Johnbull Kitchner", "2018/sc/8762", "View"},
                {"Doe Snow", "2018/sc/2786", "View"},
                {"John Snow", "2018/sc/2782", "View"},
                {"Snow Bell", "2018/sc/2784", "View"},
                {"Bell Snow", "2018/sc/2783", "View"},
                {"John Doe", "2018/sc/2783", "View"},
                {"Ella King", "2018/sc/2783", "View"},
                {"Princess Yui", "2018/sc/2783", "View"},
                {"Bull Stone", "2018/sc/2783", "View"}
            },
            new String [] {
                "Name", "Matric Number", "Assignment"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 740, 170));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Johnbull Kitchner", "2018/sc/8762", "Download"},
                {"Doe Snow", "2018/sc/2786", "Download"},
                {"John Snow", "2018/sc/2782", "Download"},
                {"Snow Bell", "2018/sc/2784", "Download"},
                {"Bell Snow", "2018/sc/2783", "Download"},
                {"John Doe", "2018/sc/2781", "Download"},
                {"Ella King", "2018/sc/2753", "Download"},
                {"Princess Yui", "2018/sc/2773", "Download"},
                {"Bull Stone", "2018/sc/2767", "Download"}
            },
            new String [] {
                "Name", "Matric Number", "Assignment"
            }
        ));
        jTable2.setOpaque(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 740, 170));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 780, 440));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText2.setBackground(new java.awt.Color(0, 0, 204));
        fgText2.setFont(new java.awt.Font("Poor Richard", 1, 12)); // NOI18N
        fgText2.setForeground(new java.awt.Color(204, 204, 204));
        fgText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText2.setText("CMS452");
        jPanel2.add(fgText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/panel student Profile.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 90));

        fgText4.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        fgText4.setForeground(new java.awt.Color(153, 153, 255));
        fgText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText4.setText("ASSIGNMENTS");
        fgText4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText4MouseExited(evt);
            }
        });
        jPanel2.add(fgText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        fgText6.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        fgText6.setForeground(new java.awt.Color(204, 204, 204));
        fgText6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText6.setText("INFORMATION");
        fgText6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText6MouseExited(evt);
            }
        });
        jPanel2.add(fgText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        fgText7.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        fgText7.setForeground(new java.awt.Color(204, 204, 204));
        fgText7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText7.setText("COURSE DOCUMENTS");
        fgText7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText7MouseExited(evt);
            }
        });
        jPanel2.add(fgText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        editProfile.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        editProfile.setForeground(new java.awt.Color(204, 204, 204));
        editProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfile.setText("Edit Profile");
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        editProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        jPanel2.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 20));

        fgText14.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        fgText14.setForeground(new java.awt.Color(204, 204, 204));
        fgText14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText14.setText("GRADES");
        fgText14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText14MouseExited(evt);
            }
        });
        jPanel2.add(fgText14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        fgText15.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        fgText15.setForeground(new java.awt.Color(204, 204, 204));
        fgText15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText15.setText("ATTENDANCE");
        fgText15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText15MouseExited(evt);
            }
        });
        jPanel2.add(fgText15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        fgText16.setBackground(new java.awt.Color(0, 0, 204));
        fgText16.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        fgText16.setForeground(new java.awt.Color(204, 204, 204));
        fgText16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText16.setText("Lecturer1");
        jPanel2.add(fgText16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 20));

        signOut.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        signOut.setForeground(new java.awt.Color(204, 204, 204));
        signOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOut.setText("Sign Out");
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutMouseExited(evt);
            }
        });
        jPanel2.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 530));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/new main blurr application background .png"))); // NOI18N
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fgText4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText4MouseClicked

    private void fgText4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText4MouseEntered
        fgText4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText4.setForeground(new java.awt.Color(153, 153, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_fgText4MouseEntered

    private void fgText4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText4MouseExited
         // TODO add your handling code here:
    }//GEN-LAST:event_fgText4MouseExited

    private void fgText6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText6MouseClicked

    private void fgText6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText6MouseEntered
        fgText6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText6.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_fgText6MouseEntered

    private void fgText6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText6MouseExited
        fgText6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText6.setForeground(new java.awt.Color(204, 204, 204));   // TODO add your handling code here:
    }//GEN-LAST:event_fgText6MouseExited

    private void fgText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText7MouseClicked

    private void fgText7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText7MouseEntered
        fgText7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText7.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_fgText7MouseEntered

    private void fgText7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText7MouseExited
        fgText7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText7.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_fgText7MouseExited

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseClicked

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        editProfile.setForeground(new java.awt.Color(153, 153, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        editProfile.setForeground(new java.awt.Color(204, 204, 204)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseExited

    private void fgText14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText14MouseClicked
lecturerGrades grade = new lecturerGrades();
        grade.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_fgText14MouseClicked

    private void fgText14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText14MouseEntered
        fgText14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText14.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_fgText14MouseEntered

    private void fgText14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText14MouseExited
        fgText14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText14.setForeground(new java.awt.Color(204, 204, 204));// TODO add your handling code here:
    }//GEN-LAST:event_fgText14MouseExited

    private void fgText15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText15MouseClicked

    private void fgText15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText15MouseEntered
        fgText15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText15.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_fgText15MouseEntered

    private void fgText15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText15MouseExited
        fgText15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText15.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_fgText15MouseExited

    private void lecturerIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerIDMouseClicked
        lecturerID.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDMouseClicked

    private void lecturerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDActionPerformed

    private void signOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseClicked
        logInFrame login = new logInFrame();
        login.setVisible(true);
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        signOut.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_signOutMouseClicked

    private void signOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseEntered
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        signOut.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_signOutMouseEntered

    private void signOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseExited
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        signOut.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_signOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturerAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturerAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturerAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturerAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturerAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel fgText12;
    private javax.swing.JLabel fgText14;
    private javax.swing.JLabel fgText15;
    private javax.swing.JLabel fgText16;
    private javax.swing.JLabel fgText2;
    private javax.swing.JLabel fgText3;
    private javax.swing.JLabel fgText4;
    private javax.swing.JLabel fgText6;
    private javax.swing.JLabel fgText7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lecturerID;
    private javax.swing.JLabel signOut;
    // End of variables declaration//GEN-END:variables
}
