/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectcms;

/**
 *
 * @author user
 */
public class logInFrame extends javax.swing.JFrame {

    /** Creates new form logInFrame */
    public logInFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lecturerID = new javax.swing.JTextField();
        StudentUserName = new javax.swing.JTextField();
        StudentPW = new javax.swing.JPasswordField();
        lecturerPW = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back2Home = new javax.swing.JLabel();
        studentLoginBtn = new javax.swing.JLabel();
        LecturerLoginBtn = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturerID.setBackground(new java.awt.Color(102, 102, 102));
        lecturerID.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lecturerID.setForeground(new java.awt.Color(204, 204, 204));
        lecturerID.setText("Please input a valid ID");
        lecturerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        lecturerID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerIDMouseClicked(evt);
            }
        });
        lecturerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerIDActionPerformed(evt);
            }
        });
        jPanel1.add(lecturerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 230, 30));

        StudentUserName.setBackground(new java.awt.Color(102, 102, 102));
        StudentUserName.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        StudentUserName.setForeground(new java.awt.Color(204, 204, 204));
        StudentUserName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        StudentUserName.setText("Please input a Username");
        StudentUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        StudentUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentUserNameMouseClicked(evt);
            }
        });
        jPanel1.add(StudentUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, 30));

        StudentPW.setBackground(new java.awt.Color(102, 102, 102));
        StudentPW.setForeground(new java.awt.Color(204, 204, 204));
        StudentPW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        StudentPW.setText("jPasswordField1");
        StudentPW.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        StudentPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentPWMouseClicked(evt);
            }
        });
        jPanel1.add(StudentPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 250, 30));

        lecturerPW.setBackground(new java.awt.Color(102, 102, 102));
        lecturerPW.setForeground(new java.awt.Color(204, 204, 204));
        lecturerPW.setText("jPasswordField1");
        lecturerPW.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        lecturerPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerPWMouseClicked(evt);
            }
        });
        jPanel1.add(lecturerPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 250, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("OR");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 60, 50));

        signupbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(0, 0, 255));
        signupbtn.setText("Sign Up.");
        signupbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupbtnMouseClicked(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 90, 30));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Don't Have an Account? ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 180, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lecturer ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 80, 20));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 70, 30));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("STUDENT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, 20));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("LECTURER");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 110, 20));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, 20));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("SIGN IN AS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 170, 40));

        back2Home.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        back2Home.setForeground(new java.awt.Color(204, 204, 204));
        back2Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back2Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/home icon.png"))); // NOI18N
        back2Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back2Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back2HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back2HomeMouseExited(evt);
            }
        });
        jPanel1.add(back2Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 80, 50));

        studentLoginBtn.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        studentLoginBtn.setForeground(new java.awt.Color(204, 204, 204));
        studentLoginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLoginBtn.setText(" Student Log in");
        studentLoginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        studentLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLoginBtnMouseExited(evt);
            }
        });
        jPanel1.add(studentLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 140, 30));

        LecturerLoginBtn.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        LecturerLoginBtn.setForeground(new java.awt.Color(204, 204, 204));
        LecturerLoginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LecturerLoginBtn.setText("Lecturer log in ");
        LecturerLoginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        LecturerLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LecturerLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecturerLoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LecturerLoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LecturerLoginBtnMouseExited(evt);
            }
        });
        jPanel1.add(LecturerLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 140, 30));

        jCheckBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("forgot password?");
        jCheckBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/mountain use.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 690, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/new main blurr application background .png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back2HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseClicked
welcomeFrame home = new welcomeFrame();
home.setVisible(true);
back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        back2Home.setForeground(new java.awt.Color(0,0,204));/// TODO add your handling code here:
    }//GEN-LAST:event_back2HomeMouseClicked

    private void back2HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseEntered
        back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        back2Home.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_back2HomeMouseEntered

    private void back2HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseExited
        back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        back2Home.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_back2HomeMouseExited

    private void studentLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLoginBtnMouseClicked
      errorLoginStudent errorS =  new errorLoginStudent();
      errorS.setVisible(true);
    }//GEN-LAST:event_studentLoginBtnMouseClicked

    private void studentLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLoginBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLoginBtnMouseEntered

    private void studentLoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLoginBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLoginBtnMouseExited

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void lecturerIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerIDMouseClicked
lecturerID.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDMouseClicked

    private void lecturerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerIDActionPerformed

    private void StudentUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentUserNameMouseClicked
      StudentUserName.setText("");
    }//GEN-LAST:event_StudentUserNameMouseClicked

    private void StudentPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentPWMouseClicked
StudentPW.setText("");
    }//GEN-LAST:event_StudentPWMouseClicked

    private void lecturerPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerPWMouseClicked
lecturerPW.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerPWMouseClicked

    private void LecturerLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecturerLoginBtnMouseClicked
LecturerLoginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        LecturerLoginBtn.setForeground(new java.awt.Color(0,0,204));   
 lecturerLoginHome home =  new lecturerLoginHome();
      home.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_LecturerLoginBtnMouseClicked

    private void LecturerLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecturerLoginBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LecturerLoginBtnMouseEntered

    private void LecturerLoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecturerLoginBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LecturerLoginBtnMouseExited

    private void signupbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbtnMouseClicked
registerChoice grade = new registerChoice();
        grade.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_signupbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LecturerLoginBtn;
    private javax.swing.JPasswordField StudentPW;
    private javax.swing.JTextField StudentUserName;
    private javax.swing.JLabel back2Home;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lecturerID;
    private javax.swing.JPasswordField lecturerPW;
    private javax.swing.JLabel signupbtn;
    private javax.swing.JLabel studentLoginBtn;
    // End of variables declaration//GEN-END:variables

}
