/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcms;

/**
 *
 * @author user
 */
public class registerChoice extends javax.swing.JFrame {

    /**
     * Creates new form registerChoice
     */
    public registerChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackgroundPanel = new javax.swing.JPanel();
        fgText2 = new javax.swing.JLabel();
        fgText1 = new javax.swing.JLabel();
        fgText3 = new javax.swing.JLabel();
        back2Home = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        BackgroundPanel.setBackground(new java.awt.Color(190, 101, 101));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText2.setBackground(new java.awt.Color(0, 0, 204));
        fgText2.setFont(new java.awt.Font("Poor Richard", 1, 60)); // NOI18N
        fgText2.setForeground(new java.awt.Color(204, 204, 204));
        fgText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText2.setText("REGISTER");
        BackgroundPanel.add(fgText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 450, 60));

        fgText1.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText1.setForeground(new java.awt.Color(204, 204, 204));
        fgText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText1.setText("Lecturers");
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText1MouseExited(evt);
            }
        });
        BackgroundPanel.add(fgText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 220, 40));

        fgText3.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        fgText3.setForeground(new java.awt.Color(204, 204, 204));
        fgText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText3.setText("Students");
        fgText3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText3MouseExited(evt);
            }
        });
        BackgroundPanel.add(fgText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 40));

        back2Home.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        back2Home.setForeground(new java.awt.Color(204, 204, 204));
        back2Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back2Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/home icon.png"))); // NOI18N
        back2Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back2Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back2HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back2HomeMouseExited(evt);
            }
        });
        BackgroundPanel.add(back2Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 80, 60));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/edited welcome bg.jpg"))); // NOI18N
        BackgroundPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseClicked
        logInFrame login = new logInFrame();
        login.setVisible(true);
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        fgText1.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_fgText1MouseClicked

    private void fgText1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseEntered
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText1.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_fgText1MouseEntered

    private void fgText1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseExited
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText1.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_fgText1MouseExited

    private void fgText3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText3MouseClicked
        studentsRegister login = new studentsRegister();
        login.setVisible(true);
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        fgText1.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_fgText3MouseClicked

    private void fgText3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText3MouseEntered

    private void fgText3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fgText3MouseExited

    private void back2HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseClicked
        welcomeFrame home = new welcomeFrame();
        home.setVisible(true);
        back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        back2Home.setForeground(new java.awt.Color(0,0,204));/// TODO add your handling code here:
    }//GEN-LAST:event_back2HomeMouseClicked

    private void back2HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseEntered
        back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        back2Home.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_back2HomeMouseEntered

    private void back2HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2HomeMouseExited
        back2Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        back2Home.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_back2HomeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel back2Home;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel fgText1;
    private javax.swing.JLabel fgText2;
    private javax.swing.JLabel fgText3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
