/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcms;

/**
 *
 * @author user
 */
public class studentChat extends javax.swing.JFrame {

    /**
     * Creates new form studentChat
     */
    public studentChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fgText17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fgText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        editProfile = new javax.swing.JLabel();
        fgText16 = new javax.swing.JLabel();
        fgText1 = new javax.swing.JLabel();
        GradesBtn = new javax.swing.JLabel();
        infoBtn = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lecturerID1 = new javax.swing.JTextField();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText17.setBackground(new java.awt.Color(0, 0, 204));
        fgText17.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        fgText17.setForeground(new java.awt.Color(204, 204, 204));
        fgText17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText17.setText("No new information, please check back later");
        jPanel4.add(fgText17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 780, 90));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 780, 440));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fgText2.setBackground(new java.awt.Color(0, 0, 204));
        fgText2.setFont(new java.awt.Font("Poor Richard", 1, 12)); // NOI18N
        fgText2.setForeground(new java.awt.Color(204, 204, 204));
        fgText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText2.setText("csc401");
        jPanel2.add(fgText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/panel student Profile.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, 90));

        signOut.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        signOut.setForeground(new java.awt.Color(204, 204, 204));
        signOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOut.setText("Sign Out");
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutMouseExited(evt);
            }
        });
        jPanel2.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, 20));

        editProfile.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        editProfile.setForeground(new java.awt.Color(204, 204, 204));
        editProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfile.setText("Edit Profile");
        editProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        jPanel2.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 20));

        fgText16.setBackground(new java.awt.Color(0, 0, 204));
        fgText16.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        fgText16.setForeground(new java.awt.Color(204, 204, 204));
        fgText16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText16.setText("Johnbull");
        jPanel2.add(fgText16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 20));

        fgText1.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        fgText1.setForeground(new java.awt.Color(153, 153, 255));
        fgText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fgText1.setText("Check Information");
        fgText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fgText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgText1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fgText1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fgText1MouseExited(evt);
            }
        });
        jPanel2.add(fgText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));

        GradesBtn.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        GradesBtn.setForeground(new java.awt.Color(204, 204, 204));
        GradesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GradesBtn.setText("Submit Assignment");
        GradesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GradesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GradesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GradesBtnMouseExited(evt);
            }
        });
        jPanel2.add(GradesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        infoBtn.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(204, 204, 204));
        infoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBtn.setText("View Grades");
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });
        jPanel2.add(infoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        docBtn.setFont(new java.awt.Font("Poor Richard", 1, 13)); // NOI18N
        docBtn.setForeground(new java.awt.Color(204, 204, 204));
        docBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        docBtn.setText("Download Course Doc");
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });
        jPanel2.add(docBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 530));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/search.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 40, 40));

        lecturerID1.setBackground(new java.awt.Color(102, 102, 102));
        lecturerID1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lecturerID1.setForeground(new java.awt.Color(204, 204, 204));
        lecturerID1.setText("Search");
        lecturerID1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerID1MouseClicked(evt);
            }
        });
        lecturerID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerID1ActionPerformed(evt);
            }
        });
        jPanel3.add(lecturerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 660, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 780, 80));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcms/new main blurr application background .png"))); // NOI18N
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseClicked
        logInFrame login = new logInFrame();
        login.setVisible(true);
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        signOut.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_signOutMouseClicked

    private void signOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseEntered
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        signOut.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_signOutMouseEntered

    private void signOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseExited
        signOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        signOut.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_signOutMouseExited

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseClicked

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        editProfile.setForeground(new java.awt.Color(153, 153, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        editProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        editProfile.setForeground(new java.awt.Color(204, 204, 204)); // TODO add your handling code here:
    }//GEN-LAST:event_editProfileMouseExited

    private void fgText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseClicked
        logInFrame login = new logInFrame();
        login.setVisible(true);
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0,0,204), 2, true));
        fgText1.setForeground(new java.awt.Color(0,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_fgText1MouseClicked

    private void fgText1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseEntered
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        fgText1.setForeground(new java.awt.Color(153, 153, 255));
    }//GEN-LAST:event_fgText1MouseEntered

    private void fgText1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgText1MouseExited
        fgText1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        fgText1.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_fgText1MouseExited

    private void GradesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseClicked

    private void GradesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseEntered
        GradesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        GradesBtn.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseEntered

    private void GradesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradesBtnMouseExited
        GradesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        GradesBtn.setForeground(new java.awt.Color(204, 204, 204));// TODO add your handling code here:
    }//GEN-LAST:event_GradesBtnMouseExited

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseClicked

    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        infoBtn.setForeground(new java.awt.Color(153, 153, 255));   // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        infoBtn.setForeground(new java.awt.Color(204, 204, 204));   // TODO add your handling code here:
    }//GEN-LAST:event_infoBtnMouseExited

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
       studentDocument grade = new studentDocument();
        grade.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
        docBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        docBtn.setForeground(new java.awt.Color(153, 153, 255));  // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
        docBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        docBtn.setForeground(new java.awt.Color(204, 204, 204));  // TODO add your handling code here:
    }//GEN-LAST:event_docBtnMouseExited

    private void lecturerID1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerID1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerID1MouseClicked

    private void lecturerID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerID1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GradesBtn;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel docBtn;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel fgText1;
    private javax.swing.JLabel fgText16;
    private javax.swing.JLabel fgText17;
    private javax.swing.JLabel fgText2;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lecturerID1;
    private javax.swing.JLabel signOut;
    // End of variables declaration//GEN-END:variables
}
